SELECT  UU.USER_ID, 
        UU.NICKNAME, 
        UU.CITY || ' ' || UU.STREET_ADDRESS1 || ' ' || STREET_ADDRESS2 AS "전체주소",
        SUBSTR(UU.TLNO, 1, 3) || '-' || SUBSTR(UU.TLNO, 4, 4) || '-' || SUBSTR(UU.TLNO, 8, 4) AS "전화번호"
FROM USED_GOODS_USER UU
INNER JOIN (SELECT WRITER_ID
            FROM USED_GOODS_BOARD
            GROUP BY WRITER_ID
            HAVING COUNT(BOARD_ID) >= 3) UG
        ON UU.USER_ID = UG.WRITER_ID
ORDER BY UU.USER_ID DESC;