SELECT AO.ANIMAL_ID, AO.ANIMAL_TYPE, AO.NAME
FROM ANIMAL_OUTS AO
INNER JOIN ANIMAL_INS AI ON AO.ANIMAL_ID = AI.ANIMAL_ID
WHERE (AI.SEX_UPON_INTAKE NOT LIKE 'Neutered%' AND AI.SEX_UPON_INTAKE NOT LIKE 'Spayed%') AND (AO.SEX_UPON_OUTCOME LIKE 'Neutered%' OR AO.SEX_UPON_OUTCOME LIKE 'Spayed%')
ORDER BY AO.ANIMAL_ID ASC;