SELECT  RR.REST_ID, 
        RI.REST_NAME, 
        RI.FOOD_TYPE, 
        RI.FAVORITES,
        RI.ADDRESS,
        ROUND(AVG(RR.REVIEW_SCORE), 2) AS SCORE
FROM REST_REVIEW RR
INNER JOIN REST_INFO RI ON RR.REST_ID = RI.REST_ID
WHERE RI.ADDRESS LIKE '서울%'
GROUP BY RR.REST_ID, RI.REST_NAME, RI.FOOD_TYPE, RI.FAVORITES, RI.ADDRESS
ORDER BY ROUND(AVG(RR.REVIEW_SCORE), 2) DESC, RI.FAVORITES DESC;