SELECT  CH.HISTORY_ID, 
        TRUNC((CH.DURATION * (CC.DAILY_FEE * (1 - NVL(CP.DISCOUNT_RATE, 0)/100)))) AS "FEE"
FROM (
      SELECT  HISTORY_ID, 
              CAR_ID, 
              TRUNC(END_DATE - START_DATE + 1) AS DURATION,
              CASE 
                  WHEN (END_DATE - START_DATE + 1) BETWEEN 7 AND 29 THEN '7일 이상'
                  WHEN (END_DATE - START_DATE + 1) BETWEEN 30 AND 89 THEN '30일 이상'
                  WHEN (END_DATE - START_DATE + 1) >= 90 THEN '90일 이상'
              END AS DURATION_TYPE
      FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
     ) CH
LEFT JOIN CAR_RENTAL_COMPANY_CAR CC 
        ON CH.CAR_ID = CC.CAR_ID
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN CP 
        ON CH.DURATION_TYPE = CP.DURATION_TYPE AND CC.CAR_TYPE = CP.CAR_TYPE
WHERE CC.CAR_TYPE = '트럭'
ORDER BY FEE DESC, CH.HISTORY_ID DESC;