SELECT A.APNT_NO, P.PT_NAME, A.PT_NO, A.MCDP_CD, D.DR_NAME, APNT_YMD
FROM APPOINTMENT A
INNER JOIN PATIENT P ON A.PT_NO = P.PT_NO
INNER JOIN DOCTOR D ON A.MDDR_ID = D.DR_ID
WHERE A.MCDP_CD = 'CS'
  AND TO_CHAR(A.APNT_YMD, 'YYYY-MM-DD') = '2022-04-13'
  AND APNT_CNCL_YN = 'N'
ORDER BY APNT_YMD;
