SELECT HOUR, COUNT(A.ANIMAL_ID) AS COUNT
FROM (SELECT LEVEL-1 AS HOUR
      FROM DUAL
      CONNECT BY LEVEL<25) H
LEFT JOIN ANIMAL_OUTS A ON H.HOUR = TO_NUMBER(TO_CHAR(A.DATETIME, 'HH24')) 
GROUP BY HOUR
ORDER BY HOUR ASC;