SELECT UB.WRITER_ID, UU.NICKNAME, SUM(PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD UB
LEFT JOIN USED_GOODS_USER UU ON UB.WRITER_ID = UU.USER_ID
WHERE STATUS = 'DONE'
GROUP BY UB.WRITER_ID, UU.NICKNAME
HAVING SUM(PRICE) >= 700000
ORDER BY TOTAL_SALES ASC;