SELECT TO_NUMBER(TO_CHAR(datetime, 'HH24')) AS "HOUR", COUNT(animal_type) AS COUNT
FROM ANIMAL_OUTS
WHERE TO_CHAR(datetime, 'HH24:MI') BETWEEN '09:00' AND '19:59'
GROUP BY TO_CHAR(datetime, 'HH24')
ORDER BY TO_CHAR(datetime, 'HH24');