SELECT II1.ITEM_ID,	II1.ITEM_NAME, II1.RARITY
FROM ITEM_INFO II1
WHERE II1.ITEM_ID IN (SELECT IT.ITEM_ID
            FROM ITEM_TREE IT
            INNER JOIN ITEM_INFO II2 ON IT.PARENT_ITEM_ID = II2.ITEM_ID 
                                    AND II2.RARITY = 'RARE')
ORDER BY II1.ITEM_ID DESC;