SELECT SUM(SCORE) AS "SCORE", HG.EMP_NO, EMP_NAME, POSITION, EMAIL
FROM HR_GRADE HG
LEFT JOIN HR_EMPLOYEES HE ON HG.EMP_NO = HE.EMP_NO
GROUP BY EMP_NO, YEAR
HAVING YEAR = 2022
ORDER BY SCORE DESC
LIMIT 1;